apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: 77+977+977+9de+/vVrvv70K #password should encrypted by echo -n "vprodbpass" | base64
  rnq-pass: 77+956y377+93p3vv73vv73XnQo=
